FROM node:18-alpine3.16

WORKDIR /app

ADD . ./

RUN : \
    && yarn install \
    && yarn build --standalone --production=true \
    && rm -rf node_modules \
    && rm package.json \
    && yarn cache clean \
    && :

ENTRYPOINT [ "node", ".output/server/index.mjs" ]
EXPOSE 3000