FROM node:lts as builder

WORKDIR /app

COPY package.json /app/
COPY yarn.lock /app/

RUN yarn install && yarn cache clean

COPY . /app/

RUN yarn build --production=true

EXPOSE 3000

CMD [ "yarn", "start" ]