#Récupération d'une image node basé sur alpine et c'est français 🇫🇷
FROM node:19-alpine

#Création d'un répertoire dans le container
WORKDIR /app

#Récupération du package.json contenant les dépendances du projet
COPY package.json ./

#Découverte de yarn qui est un gestionnaie de package comme NPM
COPY yarn.lock ./

#Installation des dépendances
RUN yarn

#Copy du fichier serveur, dockerignore avec node_modules
COPY . /app/

RUN yarn build

#Expose sur le port 8080
EXPOSE 8080:8080

#Lance en dev, pas eu le temps d'essayer une fois le code compilé avec yarn build
CMD ["yarn", "start"]