FROM golang:alpine3.16 as builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod tidy
RUN go mod download

COPY . ./

RUN go build -o api server.go

FROM alpine:latest as deploy

WORKDIR /app

COPY --from=builder /app/.env /app/
COPY --from=builder /app/api /app/

EXPOSE 3021

CMD [ "./api", "3021" ]